### ISSUE TITLE
Incorporate syntax updates

### ISSUE THREAD

**Issue by alicecima** [cmu-delphi/delphi-tooling-book#16]
The name/structure of some functions in the epi libraries seem to have changed, so parts of the tooling book's code do not currently work.

 In general:

- [x] Change `covidcast()` to `pub_covidcast()`, and adjust arguments.
- [x] Change `pivot_quantiles` to `pivot_quantiles_wider`.
- [x] Change `levels` to `quantile_levels` in `arx_args_list`.
- [x] Change `probs` to `quantile_levels` in `layer_residual_quantiles`, and `flatline_args_list`.
- [x] Change `tau` to `quantile_levels` in `quantile_reg`.

Chapter 2:

- [x] At [line](https://github.com/cmu-delphi/delphi-tooling-book/blob/4c3830c60a427abf010f890f315748f542e7584a/epidf.qmd#L52) get
#Warning messages:
1: epi_archive constructor argument `geo_type` is now ignored. Consider removing. 
2: epi_archive constructor argument `time_type` is now ignored. Consider removing. 

Chapter 6:

- [x] [Error](https://github.com/cmu-delphi/delphi-tooling-book/blob/4c3830c60a427abf010f890f315748f542e7584a/outliers.qmd#L70) because NULL is not accepted anymore for `seasonal_period`
- [x] [Error](https://github.com/cmu-delphi/delphi-tooling-book/blob/4c3830c60a427abf010f890f315748f542e7584a/outliers.qmd#L91) with `unnest(outlier_info)`

Chapter 7:

- [x] [Error](https://github.com/cmu-delphi/delphi-tooling-book/blob/4c3830c60a427abf010f890f315748f542e7584a/archive.qmd#L50) because `archive_cases_dv_subset_dt` does not exist

**Comment by dshemetov** [comment]
Thanks for this comprehensive list Alice! I know that some of these changes have been addressed in #12 (it's been a while, but I recall addressing `covidcast() -> pub_covidcast()` at least), but we just haven't gotten around to merging that in. We should probably merge that PR in and open a new one for the rest of your checklist (I don't think #12 needs to be re-reviewed). @brookslogan for visibility.

**Comment by dshemetov** [comment]
closed by #17
